// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqvznsZ-O1JPBvyenWMb-V-wOCaANfQ5c',
    appId: '1:294121953561:web:6a83855d48d02cbd2d8d88',
    messagingSenderId: '294121953561',
    projectId: 'skinsafe-ebd05',
    authDomain: 'skinsafe-ebd05.firebaseapp.com',
    storageBucket: 'skinsafe-ebd05.firebasestorage.app',
    measurementId: 'G-BXQ9RZGH0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9n7KrmIrji6nWPHIjULoeREQBbpw--kw',
    appId: '1:294121953561:android:0478bcf60516495a2d8d88',
    messagingSenderId: '294121953561',
    projectId: 'skinsafe-ebd05',
    storageBucket: 'skinsafe-ebd05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5x92UKM4FDxn4ajZoMCCOAU_1FGc3Iqs',
    appId: '1:294121953561:ios:509345d9c206cde02d8d88',
    messagingSenderId: '294121953561',
    projectId: 'skinsafe-ebd05',
    storageBucket: 'skinsafe-ebd05.firebasestorage.app',
    iosBundleId: 'com.example.skinCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5x92UKM4FDxn4ajZoMCCOAU_1FGc3Iqs',
    appId: '1:294121953561:ios:509345d9c206cde02d8d88',
    messagingSenderId: '294121953561',
    projectId: 'skinsafe-ebd05',
    storageBucket: 'skinsafe-ebd05.firebasestorage.app',
    iosBundleId: 'com.example.skinCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqvznsZ-O1JPBvyenWMb-V-wOCaANfQ5c',
    appId: '1:294121953561:web:7eeac2215f73ec132d8d88',
    messagingSenderId: '294121953561',
    projectId: 'skinsafe-ebd05',
    authDomain: 'skinsafe-ebd05.firebaseapp.com',
    storageBucket: 'skinsafe-ebd05.firebasestorage.app',
    measurementId: 'G-2RG29VGKZN',
  );
}
